context("test sample swap")

test_that("conta sample swap detection run", {

  # TODO: Add more tests (specific to functions, as well as from data.frames)

  options(warn = -1)
  expect_true(file.exists(pairing_file))
  expect_true(file.exists(shiny_file))
  expect_true(file.exists(out_dir))
  swap_out <- paste(out_dir, "swap.csv", sep = "/")
  suppressWarnings(swap(pairing_file, swap_out, shiny_file, dbsnp_targeted))

  expect_true(file.exists(swap_out))
  result <- read_data_table(swap_out, sep = ",")
  expect_true(result[, .N] == 3)
  expect_equal(result[1, DID], "D-0000004")
  expect_equal(result[2, DID], "D-0000007")
  expect_equal(result[3, DID], "D-0965032")
  expect_equal(result[1, gdna_PID], "P0034L")
  expect_equal(result[2, gdna_PID], "P002UZ")
  expect_equal(result[3, gdna_PID], "P003E0")
  expect_equal(result[1, cfdna_PID], "P00108")
  expect_equal(result[2, cfdna_PID], "P000ZU")
  expect_equal(result[3, cfdna_PID], "P001GQ")
  expect_equal(result[1, ctar_SeqSampleID], "P001080")
  expect_equal(result[1, cwgs_SeqSampleID], "P001080")
  expect_equal(result[1, gtar_SeqSampleID], "P0034L0")
  expect_equal(result[1, gwgs_SeqSampleID], "")
  expect_equal(result[2, ctar_SeqSampleID], "P000ZU0")
  expect_equal(result[2, cwgs_SeqSampleID], "P000ZU0")
  expect_equal(result[2, gtar_SeqSampleID], "P002UZ1")
  expect_equal(result[2, gwgs_SeqSampleID], "P002UZ1")
  expect_equal(result[3, ctar_SeqSampleID], "")
  expect_equal(result[3, cwgs_SeqSampleID], "")
  expect_equal(result[3, gtar_SeqSampleID], "")
  expect_equal(result[3, gwgs_SeqSampleID], "")
  expect_equal(result[1, conc_ctar_cwgs], 0.99, tolerance = 1e-2)
  expect_equal(result[2, conc_ctar_cwgs], 0.99, tolerance = 1e-2)
  expect_equal(result[3, conc_ctar_cwgs], 0, tolerance = 1e-2)
  expect_equal(result[1, conc_gtar_gwgs], 0, tolerance = 1e-2)
  expect_equal(result[2, conc_gtar_gwgs], 0.99, tolerance = 1e-2)
  expect_equal(result[3, conc_gtar_gwgs], 0, tolerance = 1e-2)
  expect_equal(result[1, conc_ctar_gtar], 1, tolerance = 1e-2)
  expect_equal(result[2, conc_ctar_gtar], 0.99, tolerance = 1e-2)
  expect_equal(result[3, conc_ctar_gtar], 0, tolerance = 1e-2)
  expect_equal(result[1, conc_cwgs_gwgs], 0, tolerance = 1e-2)
  expect_equal(result[2, conc_cwgs_gwgs], 0.99, tolerance = 1e-2)
  expect_equal(result[3, conc_cwgs_gwgs], 0, tolerance = 1e-2)
  expect_equal(result[1, cwgs_final_stein], 0.33, tolerance = 1e-2)
  expect_equal(result[2, cwgs_final_stein], 0.32, tolerance = 1e-2)
  expect_equal(result[3, cwgs_final_stein], 0, tolerance = 1e-2)
  options(warn = 0)
})
