// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// intersect_snps
void intersect_snps(const char* tsv_filename, const char* out_tsv_filename, const char* vcf_filename, bool non_dbSNP, bool DEBUG);
RcppExport SEXP conta_intersect_snps(SEXP tsv_filenameSEXP, SEXP out_tsv_filenameSEXP, SEXP vcf_filenameSEXP, SEXP non_dbSNPSEXP, SEXP DEBUGSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type tsv_filename(tsv_filenameSEXP);
    Rcpp::traits::input_parameter< const char* >::type out_tsv_filename(out_tsv_filenameSEXP);
    Rcpp::traits::input_parameter< const char* >::type vcf_filename(vcf_filenameSEXP);
    Rcpp::traits::input_parameter< bool >::type non_dbSNP(non_dbSNPSEXP);
    Rcpp::traits::input_parameter< bool >::type DEBUG(DEBUGSEXP);
    intersect_snps(tsv_filename, out_tsv_filename, vcf_filename, non_dbSNP, DEBUG);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"conta_intersect_snps", (DL_FUNC) &conta_intersect_snps, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_conta(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
