# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Intersect a TSV file with VCF file and write a TSV output
#' that contains maf values for each SNP in the TSV file.
#' In the process, remove multiple-allele SNPs if the option
#' is turned on.
#'
#' @param tsvFileName string name of input TSV file
#' @param outTsvFileName string name of output TSV file
#' @param vcfFileName string dbsnp VCF file name to be intersected
#' @param DEBUG boolean whether to print out messages
#' @return null
#'
#' @export
intersect <- function(tsvFileName, outTsvFileName, vcfFileName, nonDbSnp = FALSE, DEBUG = FALSE) {
    invisible(.Call('conta_intersect', PACKAGE = 'conta', tsvFileName, outTsvFileName, vcfFileName, nonDbSnp, DEBUG))
}

