# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Intersect a TSV file with VCF file and write a TSV output
#' that contains maf values for each SNP in the TSV file.
#' In the process, remove multiple-allele SNPs if the option
#' is turned on.
#'
#' @param tsv_filename string name of input TSV file
#' @param out_tsv_filename string name of output TSV file
#' @param vcf_filename string dbsnp VCF file name to be intersected
#' @param DEBUG boolean whether to print out messages
#' @return null
#'
#' @export
intersect_snps <- function(tsv_filename, out_tsv_filename, vcf_filename, non_dbSNP = FALSE, DEBUG = FALSE) {
    invisible(.Call('conta_intersect_snps', PACKAGE = 'conta', tsv_filename, out_tsv_filename, vcf_filename, non_dbSNP, DEBUG))
}

